"""Run the full pipeline.  python run.py [--data data] [--work work]"""
import argparse, json, sys, time
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from pipeline.orchestrator import run_pipeline, GateFailure
from pipeline.ingest import IngestRefused

CFG = dict(
    max_quarantine_frac=0.05, max_flagged_frac=0.10, stale_months=3,
    high_risk_pfail=0.5, mc_reps=200, seed=11,
    tat=dict(mu=0.3, sigma=0.4, p_spare=0.85, backorder=2.0),  # lognormal months
)

if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--data", default="data"); ap.add_argument("--work", default="work")
    ap.add_argument("--publish-examples", action="store_true",
                    help="copy the run's summary and a deterministic ledger sample into results/")
    a = ap.parse_args()
    meta = json.loads((Path(a.data) / "meta.json").read_text())   # n_months, horizon, component catalogue
    CFG.update(meta)
    t0 = time.time()
    try:
        st = run_pipeline(Path(a.data), Path(a.work), CFG)
    except (GateFailure, IngestRefused) as e:
        print(f"STOPPED: {e}"); sys.exit(2)
    for s in st.stage_log:
        print(f"  {s['stage']:8s} {s['status']:7s} {s.get('sec', '')}")
    print(f"done in {time.time()-t0:.0f}s; degradations: {len(st.degradations)}")
    print(open(Path(a.work) / "summary.md").read())
    if a.publish_examples:
        # The committed example artifacts get a generating command, so they
        # cannot silently rot into describing a run the code no longer does.
        import shutil
        results = Path("results"); results.mkdir(exist_ok=True)
        shutil.copyfile(Path(a.work) / "summary.md", results / "summary_example.md")
        chans = json.loads((Path(a.work) / "ledger.json").read_text())["channels"]
        picks, seen = [], set()
        for chan in sorted(chans, key=int):
            key = (chans[chan]["damage_basis"], chans[chan]["sensor_status"])
            if key not in seen:
                seen.add(key); picks.append(chan)
        lines = ["# Ledger examples", "",
                 "Generated by `python run.py --publish-examples`: the lowest-numbered",
                 "channel for each (damage basis, sensor status) combination present in",
                 "the run, verbatim from `work/ledger.json`.", ""]
        for chan in picks:
            rec = chans[chan]
            lines += [f"## channel {chan} - {rec['tail']} {rec['component']} "
                      f"({rec['damage_basis']}, sensor {rec['sensor_status']})", "",
                      "```json", json.dumps(rec, indent=1), "```", ""]
        (results / "ledger_examples.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"published summary and {len(picks)} ledger examples into results/")
